Boa tarde, pessoal 

RECUPERAÇÃO FINAL DE MATEMÁTICA BÁSICA - 2 ANO C

ASSUNTO: FUNÇÃO E EQUAÇÃO DO 1 GRAU

NOMES:

BRYAN VINICIUS DE LIMA BONFIM	
ITALO DE BARROS DA SILVA	
JOSE FRANCISCO MARTINS PAIS DE LIRA	
MARIA CLARA DA SILVA CABRAL	
PABLO STHYVAN TAVARES DE LIMA	
RAQUELE BARBOSA BESERRA	
SANDREANE BARBOSA DA SILVA	
VIVIANE DE OLIVEIRA ARAUJO	
LARISSA MONIKE PEREIRA MACENA
