Bom dia, Fred 
A declaração que os seguinte estudante estão matriculados no ensino médio 


1º Ano B: 
INGRID IARA DA SILVA BRITTO
MARIA JAMILE ARCOVERDE DA SILVA

1º Ano C: 
VITOR MIGUEL VIEIRA DE MORAIS

2º Ano B: 
BEATRIZ DOS SANTOS LIMA
THALYTA CLARA RODRIGUES LEITE

3º Ano B: 
ALBERTO FERREIRA DA SILVA
DANIEL KENNEDY DOMINGOS DA SILVA
IANDRA VALERIA DE OLIVEIRA VIANA
FILIPE DE SOUZA JORGE
RAYSSA ALBUQUERQUE SILVA



