| ESTUDANTES:                   | NOTAS: |
| ANA ALICE HENRIQUE DA SILVA   | 6.0    |
| ELIETE CAVALCANTI DA SILVA    | NF     |
| EWERTON JOHN BEZERRA DA SILVA | NF     |
| JEFFERSON DE MOURA LIMA       | NF     |
| JOICE KELLY FERREIRA FREIRE   | 8.0    |
| JOSE THIAGO DOS SANTOS SILVA  | NF     |
| MAX DOUGLAS MELO MOREIRA      | 6.0    |
| CAROLINE BEZERRA ALVES        | NF     |
