Boa tarde, pessoal 

RECUPERAÇÃO FINAL DE MATEMÁTICA - 1 ANO B

ASSUNTO: FUNÇÃO E EQUAÇÃO DO 1 GRAU

NOMES:

ADRIELLE TENORIO ARAUJO	
DIEGO LEITE DA SILVA	
DIEGO SILVA MOURA SANTOS	
JOAO GABRIEL BARBOSA DOMINGOS	
JOÃO VITOR DE SANTANA GOMES	
KAUA DE LIMA BRITTO	
LUCAS VINICIUS SIMAO DIAS	
MARIA CLARA LIRA DA SILVA	
MATEUS VICTOR EVANGELISTA DA SILVA	
NAYNE RAQUELE DA SILVA HONORIO	
ROBERTO LUCAS DOS SANTOS JULIAO	
YASMIM DE ARAUJO CAVALCANTI	
YTALO KAWAN SOUZA DA SILVA	
NICKOLY VICTORIA GERMANO DA SILVA	
LARA GOMES DA SILVA 	
SAMUEL DOS SANTOS SILVA
