| ESTUDANTES                           | NOTAS: |
| ADRYAN KAUA DOS SANTOS SANTANA       | NF     |
| AMANDA LOPES DA SILVA                | NF     |
| CAMILA BALTAZAR DA SILVA             | 1.0    |
| GABRIELLY GOMES NUNES                | NF     |
| ILLIAN VINICIUS FELIX SANTANA        | 1.0    |
| JOSE ARIEL BARBOSA DA SILVA          | 1.0    |
| JOSE VITO FELIX CAVALCANTE           | NF     |
| LUIZ GUSTAVO FELIX BORGES            | 1.0    |
| MARIA GISLANY FERREIRA DE BRITO      | 8.0    |
| MARIA SAYORE DA SILVA ALENCAR        | 6.0    |
| RAFAEL MORAES DE ARAUJO              | 1.0    |
| RAYSSA SAMARA BENICIO DOS SANTOS     | 6.0    |
| THIAGO LAVANDEIRA DA SILVA MIRANDA   | 1.0    |
| VANDERSON DE BARROS CAVALCANTI       | 1.0    |
| WEVERTON BARBOSA OLIVEIRA            | 1.0    |
| YASMIM VICTORIA SIQUEIRA CALU        | NF     |
| YSLLY THAUANNY DE OLIVEIRA SILVA     | 6.0    |
| YURI RAPHAEL GOMES DA SILVA          | 1.0    |
| APARECIDA YASMIN GOMES DA SILVA LIMA | 1.0    |
| KAUA GABRIEL BEZERRA RAMOS           | NF     |
| MARIA VITORIA DA SILVA CIPRIANO      | NF     |
| YASMIN APARECIDA GOMES DA SILVA      | NF     |
| DAVID GABRIEL SOUZA DA SILVA         | NF     |
